### PR TITLE
Revamped README

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
- Added Overview
- Added an actual description for the program
- Fixed formatting (bullet points, bash formatting, etc)
- Hyperlinked some stuff
- Capitalized letters

- Changed Vibrant Linux to vibrantLinux: just in case the name of the program is actually vibrantLinux, the whole README should call it as vibrantLinux. I made a seperate commit so it is easy to choose. Enjoy.

### CODE REVIEW

**Comment by zee-mzha** [comment]
Thanks for doing this but i'd already made changes to the README and forgot to push them earlier today. The README in this pull request is outdated now as it contains incorrect info (not all required libraries are included, xcb + ewmh is not longer optional)

**Comment by TheEvilSkeleton** [comment]
Do I modernize the merge request or will you close it? (Sorry this isn't really clear to me)

**Comment by zee-mzha** [comment]
I left it open to you, if you feel like there's anythings that need to be changed you can feel free to modernize them and I will take a look at them and merge them if they are good, if not then the pull request will be closed

**Comment by TheEvilSkeleton** [comment]
> xcb + ewmh is not longer optional

Does this mean that they are required, or removed?

**Comment by zee-mzha** [comment]
oh jeez, I didn't even notice this was a commit to master. You can find the most up to date version in the v2_WiP branch. xcb and xcb-ewmh are required. I'll be closing this since any updates right now are going to that branch

**Pull request closed without merging**
