### PR TITLE
Preparations for Flatpak build

### PR DESCRIPTION
**Pull request by Scrumplex**
In preparations for a Flatpak package I will be maintaining I need adjust a few things, so that everything is according to FreeDesktop specifications.

Flatpak Requirements are here: https://docs.flatpak.org/en/latest/conventions.html

### CODE REVIEW

**Comment by Scrumplex** [comment]
Created a prototype Flatpak at https://github.com/Scrumplex/vibrantLinux-flatpak

I plan to add this to Flathub eventually

**Comment by zee-mzha** [comment]
sorry I've been MiA, a combination of life and lost interest in the project got in the way, and unfortunately I don't think I can or want to keep working on it. I'll keep approving merge requests from you, and if you'd like I can archive this repo and have it redirect to the organization's page or your page and give you control. Thank you for still putting in the time and effort to make this project work.

**Comment by Scrumplex** [comment]
> and have it redirect to the organization's page or your page and give you control

Thanks for the offer, but I think I also won't be able to maintain it much. I switched to Wayland a few months ago, and currently there is no way to do this stuff on any Wayland compositor, so I won't even be able to test this.

I am just working on this now, as I have seen many people get frustrated by the build process (even I didn't get it right first try in a Ubuntu VM) and just wanted to package this as a Flatpak to end all of this frustration :D

I might also add stuff to support AppImages and everyone should be satisfied by then.

Happy new year / Have a happy new year!

**Comment by Scrumplex** [comment]
After thinking about it, maybe it would actually be better if we move this into @Vibrance-org. That way I can keep working on it without needing to nag you for small PRs

**Comment by zee-mzha** [comment]
that sounds good to me, you're already an owner on there so you should have all the privileges you need. Let me know once you do and I'll update this repo.

**Comment by Scrumplex** [comment]
Yes we are both owners on there. So should be fine. I wouls suggest you just move this project using GitHub's built-in feature. That way all issues will also be moved and GitHub will create a redirect from here to there

**Comment by Scrumplex** [comment]
The option is in the project's settings at the end (where the buttons for deleting and archiving are)

**Pull request merged**
